"""create initial tables

Revision ID: 3e60aea5a6bd
Revises: 3c9be6c9f8fb
Create Date: 2026-07-20 19:31:11.465316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e60aea5a6bd'
down_revision: Union[str, Sequence[str], None] = '3c9be6c9f8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_locations', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('core_locations', sa.Column('short_name', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('core_locations_Name_key'), 'core_locations', type_='unique')
    op.drop_constraint(op.f('core_locations_Short name_key'), 'core_locations', type_='unique')
    op.create_unique_constraint(None, 'core_locations', ['name'])
    op.create_unique_constraint(None, 'core_locations', ['short_name'])
    op.drop_column('core_locations', 'Short name')
    op.drop_column('core_locations', 'Name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_locations', sa.Column('Name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('core_locations', sa.Column('Short name', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'core_locations', type_='unique')
    op.drop_constraint(None, 'core_locations', type_='unique')
    op.create_unique_constraint(op.f('core_locations_Short name_key'), 'core_locations', ['Short name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('core_locations_Name_key'), 'core_locations', ['Name'], postgresql_nulls_not_distinct=False)
    op.drop_column('core_locations', 'short_name')
    op.drop_column('core_locations', 'name')
    # ### end Alembic commands ###
