"""create initial tables

Revision ID: 6399f4617486
Revises: b7b89f3a3b2f
Create Date: 2026-07-20 18:02:35.399816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6399f4617486'
down_revision: Union[str, Sequence[str], None] = 'b7b89f3a3b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_locations', sa.Column('Short name', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('core_locations_Short Name_key'), 'core_locations', type_='unique')
    op.create_unique_constraint(None, 'core_locations', ['Short name'])
    op.drop_column('core_locations', 'Short Name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_locations', sa.Column('Short Name', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'core_locations', type_='unique')
    op.create_unique_constraint(op.f('core_locations_Short Name_key'), 'core_locations', ['Short Name'], postgresql_nulls_not_distinct=False)
    op.drop_column('core_locations', 'Short name')
    # ### end Alembic commands ###
