"""create initial tables

Revision ID: b7b89f3a3b2f
Revises: 41572d2e3cfb
Create Date: 2026-07-20 17:33:02.930960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b89f3a3b2f'
down_revision: Union[str, Sequence[str], None] = '41572d2e3cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_locations', sa.Column('Name', sa.String(length=100), nullable=False))
    op.add_column('core_locations', sa.Column('Short Name', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('core_locations_name_key'), 'core_locations', type_='unique')
    op.drop_constraint(op.f('core_locations_short_name_key'), 'core_locations', type_='unique')
    op.create_unique_constraint(None, 'core_locations', ['Short Name'])
    op.create_unique_constraint(None, 'core_locations', ['Name'])
    op.drop_column('core_locations', 'name')
    op.drop_column('core_locations', 'short_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_locations', sa.Column('short_name', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.add_column('core_locations', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'core_locations', type_='unique')
    op.drop_constraint(None, 'core_locations', type_='unique')
    op.create_unique_constraint(op.f('core_locations_short_name_key'), 'core_locations', ['short_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('core_locations_name_key'), 'core_locations', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('core_locations', 'Short Name')
    op.drop_column('core_locations', 'Name')
    # ### end Alembic commands ###
